{{- if .Values.persistence.context.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "assops.fullname" . }}-context
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.context.storageClassName }}
  storageClassName: {{ .Values.persistence.context.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.context.size }}
---
{{- end }}
{{- if .Values.persistence.bareRepos.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "assops.fullname" . }}-bare-repos
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.bareRepos.storageClassName }}
  storageClassName: {{ .Values.persistence.bareRepos.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.bareRepos.size }}
---
{{- end }}
{{- if .Values.persistence.ssh.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "assops.fullname" . }}-ssh
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.ssh.storageClassName }}
  storageClassName: {{ .Values.persistence.ssh.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.ssh.size }}
---
{{- end }}
{{- if and .Values.persistence.kubeconfigs.enabled (not .Values.persistence.kubeconfigs.existingSecretName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "assops.fullname" . }}-kubeconfigs
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.kubeconfigs.storageClassName }}
  storageClassName: {{ .Values.persistence.kubeconfigs.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.kubeconfigs.size }}
---
{{- end }}
{{- if .Values.persistence.backups.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "assops.fullname" . }}-backups
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.backups.storageClassName }}
  storageClassName: {{ .Values.persistence.backups.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
{{- end }}
