{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "assops.secretName" . }}
  labels:
    {{- include "assops.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseURL | quote }}
  ASSOPS_JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  ASSOPS_WEBHOOK_SECRET_KEY: {{ .Values.secret.webhookSecretKey | quote }}
  ASSOPS_ADMIN_EMAIL: {{ .Values.secret.adminEmail | quote }}
  ASSOPS_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  ASSOPS_APPROVAL_WEBHOOK_TOKEN: {{ .Values.secret.approvalWebhookToken | quote }}
  ASSOPS_CLOUDFLARE_QUEUES_API_TOKEN: {{ .Values.secret.cloudflareQueuesAPIToken | quote }}
  ASSOPS_CLOUDFLARE_TASK_PRODUCER_TOKEN: {{ .Values.secret.cloudflareTaskProducerToken | quote }}
  ASSOPS_GITHUB_ACTIONS_READ_TOKEN: {{ .Values.secret.githubActionsReadToken | quote }}
  ASSOPS_ARGO_READ_TOKEN: {{ .Values.secret.argoReadToken | quote }}
  ASSOPS_GITHUB_TEMPLATE_TOKEN: {{ .Values.secret.githubTemplateToken | quote }}
  ASSOPS_GITEA_TEMPLATE_TOKEN: {{ .Values.secret.giteaTemplateToken | quote }}
{{- end }}
