apiVersion: v1
kind: Service
metadata:
  name: {{ include "assops.fullname" . }}-gateway
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "assops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
---
{{- if .Values.legacyWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "assops.fullname" . }}-worker-health
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  ports:
    - name: health
      port: 8081
      targetPort: health
  selector:
    {{- include "assops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "assops.fullname" . }}-node-worker-health
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  ports:
    - name: health
      port: 8082
      targetPort: health
  selector:
    {{- include "assops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node-worker
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "assops.fullname" . }}-web
  labels:
    {{- include "assops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
  selector:
    {{- include "assops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
