apiVersion: v1
kind: Namespace
metadata:
  name: assops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assops-promoter
  namespace: assops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assops-promoter
  namespace: assops
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assops-promoter
  namespace: assops
subjects:
  - kind: ServiceAccount
    name: assops-promoter
    namespace: assops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assops-promoter
